version: '3'
services:
  zookeeper:
    image: 'zookeeper:3.7.0'
    container_name: 'zookeeper'
    ports:
      - '2181:2181'
    networks:
      - mi-red

  kafka:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'kafka'
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    networks:
      - mi-red

networks:
  mi-red:
    external: true
